### ISSUE TITLE
VSCODE and zopeneditor settings

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#201]
Hi, i am on the newest Z open Editor version (1.4.1) and on Vscodium 1.62.3.

![grafik](https://user-images.githubusercontent.com/86772851/145974497-49152f9a-52e5-44cb-93c9-9adc5266033f.png)

e.g. the zopeneditor.propertygroups setting is working at workspace level (in our case in a *.code-workspace json dataset).
That would allow us to make a somewhat portable installation without the need to update files in the user Folder. (C:\Users\xxxxxx\AppData\Roaming\VSCodium\User)

## Description of the enhancement requested

In terms of automation it would be nice if all z open editor settings could be applied at workspace level, and not be at user level...

Thank you!

**Comment by davidkcoblentz** [comment]
I agree.  I have the same issue when I roll VS Code out to all developers it would be nice to set certain settings like property groups at the Work Space level.

**Comment by phaumer** [comment]
@kraabrsg and @davidkcoblentz this works already (unless I misunderstand your requirement). You can enter [property groups into workspace settings](https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#setting-ibm-z-open-editor-property-groups-in-multi-root-workspaces) in your workspace's .vscode folder as `settings.json` instead of user settings. You can use glob patterns to define relative pathnames for the files to be found.

This file can then be shared in your SCM with other users. I could also image that if you do not use and SCM that you could place that settings file in a data set and user's can download it with Zowe Explorer before starting their work; assuming that they would use the same folder names for local files. 

The other solution we provide is [ZAPP files](https://ibm.github.io/zopeneditor-about/Docs/zapp.html), which are stored in the workspace as well. We consider to actually at some point to use ZAPP files only for property groups and deprecate defining them in VS Code settings entirely. What would you think about that?

See you sample repo with different settings using VS Code workspace settings, ZAPP YAML and ZAPP JSON as alternatives to user settings: <https://github.com/IBM/zopeneditor-sample>

**Comment by kraabrsg** [comment]
Hi @phaumer thanks for getting back on this.
![grafik](https://user-images.githubusercontent.com/86772851/146321084-22d2d1c7-51b3-4f86-80e0-91cb947da55b.png)

I tried what you suggested, but that did not work here, in a multirootworkspace setup, as can be seen in the screenshot (the settings only apply in users folder or, like it is now in the *.code-workspace file as "global") -> do i miss something here ?

We don't use a traditional SCM here, the way it is working now that the cli, the powershells, and other json datasets update while starting vscodium.(copy over or update the files via powershell). In the future this should work with a GIT REPO. We update these settings by changing the host dataset names (syslib) when changing product/release via powershell.

As for the ZAPP File, you also commented on that here: https://github.com/IBM/zopeneditor-about/issues/152
I don't see that much of an advantage using ZAPP, we would mayhap change to it if a "mapping" of folders(in vscodium) to hostdatasets(for resolving copybooks) would be possible -> more product / release combinations at a time (like it is working now with IDZ / RDZ and rse).

By the way, if would want to try the rse plugin, what license do they have?

Thanks!

**Comment by kraabrsg** [comment]
As a follow up on this another suggestion:
Would it be possible to add "propertygrous to folder settings also? (currently it is only visible in "User" and "Workspace" )

![grafik](https://user-images.githubusercontent.com/86772851/148228053-56da142d-410a-4122-9a04-2f5d8b7e57a7.png)

Like "Userbuild Workspace Settings"

This would allow us to write different mvs datasets in  propertygroups per folder (product and release) via a seperate settings.json.

Thank you!

**Comment by FALLAI-Denis** [comment]
Hi,

We use the zapp.yaml (or zapp.json) files instead of the VS Code settings files precisely because this allows us to be independent of the VS Code configuration.
The zapp.yaml files are declared in the Workspace, in fact in the Git repository used to manage our sources.
So we are sure that all users share the same configurations for the properties groups.

If you are not using Git, then you need a mechanism that downloads the zapp.yaml file from your SCM, or instructs users to manually download the zapp.yaml file.
More and more SCMs offer a Git interface, natively or through add-ins.

For last question, I open issues:
Need to have contextual property groups (relative to Git branches) #97
Need to have contextual property groups (relative to nature of program) #98
Reorganization of the design of property groups #99
All languages - Relative path to current edited file for local syslib and location in settings.json / zapp.yaml #163

**Comment by kraabrsg** [comment]
Hi @FALLAI-Denis thanks for your comments, changing to the yaml file would be possible, we now change the code-workspace file via powershell, if the user wants to change product/release, the PO Datasets(propertygrous) are changed.
We would like to have a seperation relateded to a folder -> product/release PO Datasets should be mappable to a folder (so the correct copybooks of the current product/release are shown).

**Comment by phaumer** [comment]
Hello. With v2.1.1 we made some updates to property groups resolutions and user build for multi-root workspaces using zapp. I created a multi-root workspace example here to demonstrate a simple setup: https://github.com/IBM/zopeneditor-sample/tree/wazi-main/multiroot 

I am closing this item now, but please evaluate the new solution and open new items for any problems or enhancement suggestions.
