### ISSUE TITLE
COBOL Parsing Error because of Period in 72 and Standard Numbering Present

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#202]
## Development environment used

Version: 1.63.1 (user setup)
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:54.292Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763

### Detailed steps for reproducing the problem:

1. Open a COBOL source that has standard numbering in position 73-80.
2. Create a line of code in the Data Division that ends with it's period in position 72.
3. This should produce a parsing error that isn't accurate.

### Observed behavior

Data Division statement that creates a parsing error
![image](https://user-images.githubusercontent.com/80063515/146077045-132e6a0e-dea1-4c6f-bb7a-d471d69c257e.png)

When the Unnumbering action is applied so that numbering is removed then the errors go away.
![image](https://user-images.githubusercontent.com/80063515/146077218-561ee325-419d-44fe-9ac8-beaec7a1c602.png)

Procedure Division Code works correctly
![image](https://user-images.githubusercontent.com/80063515/146081079-8bb3c26d-b43f-4bbb-a3bb-79154d58f60a.png)

### Expected behavior

Expected no parsing errors as if no numbers were present.

COBOL Compile Listing of lines above with no errors. 
![image](https://user-images.githubusercontent.com/80063515/146080010-52d50463-7944-47ee-92aa-b1ea8e6cf7a0.png)

**Comment by FALLAI-Denis** [comment]
Hi,

I think this issue can be resolved by applying enhancement describe in #182 [COBOL - Improve text colorization for syntax highlighting by textmate grammar](https://github.com/IBM/zopeneditor-about/issues/182).

**Comment by davidkcoblentz** [comment]
Thank you for the information!

Apologies, but I am not familiar with TextMate.  I will be reading about it as I can to learn it but in your response in #182<https://urldefense.com/v3/__https:/github.com/IBM/zopeneditor-about/issues/182__;!!OgnrLJOUc50AAzM!em86hQfzZGXaC9UCHi1AH14gbkhiFIGqc6aM1BWM5RI6XS2VETnHBgXS7NRpiDKvrg$> COBOL - Improve text colorization for syntax highlighting by textmate grammar<https://urldefense.com/v3/__https:/github.com/IBM/zopeneditor-about/issues/182__;!!OgnrLJOUc50AAzM!em86hQfzZGXaC9UCHi1AH14gbkhiFIGqc6aM1BWM5RI6XS2VETnHBgXS7NRpiDKvrg$> I see your example and what to do but where do I make the changes and what is the TextMate code to divide the line into 3 sections. I tried looking up TextMate in the Command Palette and clicking on the settings but don’t yet understand the result that I am looking at. Am I missing something obvious?

Thank you,
***@***.***

**Comment by FALLAI-Denis** [comment]
Hi @davidkcoblentz,

You can't really make any changes because COBOL textmate grammar comes with the Z Open Editor extension.

Optionally you could extend the textmate grammar that comes with the Z Open Editor extension by developing another extension, but it is still complicated and it is not certain that this solves the problem.

In issue #182, I developed a minimal textmate grammar, and overwrite the file that came with the extension. This is something that is still possible for testing, but not for production use.

---

Regarding the management of the COBOL point, I searched in the reference documentation, but I did not find the information sought.

The COBOL end-of-sentence delimiter is the dot-space sequence, not the dot alone.
However, it seems to me that there is a tolerance when this point appears in column 72: in this case it does not have to be followed by a space.

**Comment by phaumer** [comment]
Fixed in Z Open Editor v2.0.0
