### ISSUE TITLE
Support SQLCA and SQLDA in mixed case. Investigate possible memory leaks and high CPU usage when include file are not found.

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#208]
We have here again a problem with some kind of memory leak. Unfortunatly i could not find log files to narrow down the problem. How can i enable the profiling? Where to find java log files? We use jdk-11.0.2  (One file opened, which can be seen on the screenshot, z open editor Version 1.4.1, WIN 10)
`
"zopeneditor.JAVA_HOME": "C:\\xxxxx\\java\\jdk-11.0.2",
`

![grafik](https://user-images.githubusercontent.com/86772851/148178216-763ddbd4-72e1-40be-a9a0-64680b29f879.png)

After a restart of VSCODIUM everything seems to be fine again:

![grafik](https://user-images.githubusercontent.com/86772851/148178723-c8e0f532-95fc-4afe-bb69-23f5fc839d9a.png)

The only thing we found was that  Zopeneditor logs a lot of warnings because of the not found of "EXEC SQL INCLUDE SQLCA"
![grafik](https://user-images.githubusercontent.com/86772851/148187885-558e2393-4c58-4b21-98b8-02a8f80a9dea.png)

We are using "zopeneditor.propertygroups" in our settings, i think there is no way to exclude this member??? Wouldn't it be better to not scan this Member bei Z open editor (assuming to the Documentation https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#enforcing-case-sensitive-file-name-matching it is excluded)??? 

Causes a lot of S222(for each lib in propertygroups)
![grafik](https://user-images.githubusercontent.com/86772851/148220016-8c85e2fc-7a70-40bd-a9a7-5a251c60da3d.png)

somewhat related to #134 

Thanks!

_Originally posted by @kraabrsg in https://github.com/IBM/zopeneditor-about/issues/195#issuecomment-1005450182_

**Comment by phaumer** [comment]
@kraabrsg thanks. That's why this community is so valuable to us. All our tests only use SQLCA in uppercase so I suspect that we do not check this case sensitive, which we must fix. 

About profiling the memory usage, it would be something we have to do. So the more info you can provide for how to reproduce the memory growth the better. (We will start by issuing include file requests with not found results.)

**Comment by kraabrsg** [comment]
Hi @phaumer thanks for getting back on this. Fixing SQLCA maybe is allready part of the Problem??? (that alone would help a lot).
Just tried to to reproduce it with the program of the screenshot, but unfortunatly i can't :-( 
When we find more facts i will post it here.

**Comment by davidkcoblentz** [comment]
[](https://github.com/schoko11)[](https://github.com/davidkcoblentz)[](https://github.com/davidkcoblentz)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/schoko11)[](https://github.com/davidkcoblentz)[](https://github.com/)I was editing COBOL source, I accidentally held down ENTER long enough to insert 10 or so blank lines, then hit CTRL+Z many times to reverse the 10 blank lines but instead got this error.

[Error - 7:27:15 PM] Request textDocument/documentLink failed.
Message: Internal error.
Code: -32603
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: Java heap space

Extension version: 1.4.1
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

System Info
A/B Experiments

**Comment by phaumer** [comment]
Fixed the mixed case issue as well the performance problem in v2.0.0.
