### ISSUE TITLE
Can pull (download) PDS member from z/OS but there's no upload cloud icon to save back to z/OS

### ISSUE THREAD

**Issue by cds-ari** [IBM/zopeneditor-about#24]
Problem description revised:

Running z/OS 2.3. Installed latest ZOWE OE extension for VS Code and ZOWE CLI on Win10 Pro, also fully updated.

CLI working because I can list PDSs and their members and pull them in. CLI profile is for TSO user with full UPDATE access on z/OS side. From a Windows command prompt window, using the "zowe zos-files upload file-to-data-set" CLI command and the same profile name, I can also successfully add/update a member in the same PDS I'm try to edit/save in the ZOWE OE. So the problem isn't with RACF or with the CLI.

Pull from mainframe (down arrow) cloud icon appears to right of member name in ZOWE Explorer window but there's not save to mainframe (up arrow) cloud icon. I can, however, save to mainframe by closing the file and being prompted to save. That updates on the z/OS. However, where's the upload cloud icon?

**Comment by phaumer** [comment]
@cds-ari thanks for trying our extensions.  The git repo for filing Zowe Explorer issue is here: <https://github.com/zowe/vscode-extension-for-zowe>. This repo is for the Z Open Editor.

The Cloud icon in Zowe Explorer is performing the "Pull from Mainframe" operation that you also see in the context menu when you right-click a file. Open and saving files does not require special icons, but uses the regular VS Code operations. You just click the file to get it and open it in the editor and Cmd-S or Ctrl-S or menu File > Save to save it back to z/OS.  Pull from Mainframe is only intended to load the latest from z/OS in case you want to restore the file losing your changes or if you know that another client changed it since you opened it.  If another user save in parallel it will actually check and show you a diff viewer as well.
