### ISSUE TITLE
run program for beginners

### ISSUE THREAD

**Issue by MatthiasBencic** [IBM/zopeneditor-about#26]
hello, its my first time using VSC and im just curious, what files do you need to run a pl/i program? as right now i just have created a workspace folder and the .pli file. I've also set the JAVA_HOME variable and installed the SDK... what am i missing to run it?

**Comment by MatthiasBencic** [comment]
> 
> 
> hello, its my first time using VSC and im just curious, what files do you need to run a pl/i program? as right now i just have created a workspace folder and the .pli file. I've also set the JAVA_HOME variable and installed the SDK... what am i missing to run it?

im now further.. relaunching VSC helped so now i can compile.
but to run it says "Cannot launch program {path}; setting the 'outFiles' attribute might help."
and when i set the outFiles attributes it states "Cannot launch program {path} because corresponding JavaScript cannot be found." although i have no output files in my pl/i program. how can i run it?

**Comment by phaumer** [comment]
@MatthiasBencic thanks a lot for trying our extension.  The NoClassDefFound error people typically get when they use a Client JRE instead of the required Server JRE or JDK. (see https://ibm.github.io/zopeneditor-about/Docs/getting_started.html#prerequisites)

In terms of running a PL/I program: we do not provide any local compile and run options with this extension. The scope is IBM Enterprise language development that requires compiling on a mainframe using z/OS (https://www.ibm.com/us-en/marketplace/pli-compiler-zos). Our sample at https://github.com/ibm/zopeneditor-sample has the JCL required to compile and run our PL/I example programs; so you would have to do something similar. 

If you do not have access to a mainframe then there are several ways such as through universities or our own Master the Mainframe program: https://www.ibm.com/it-infrastructure/z/education/master-the-mainframe-contest
