### ISSUE TITLE
How to avoid S222 abends when receiving a lot of .cpy files?

### ISSUE THREAD

**Issue by bearou** [IBM/zopeneditor-about#27]
Openning a COBOL program triggers a "background task" fetching all referenced copybooks. 
However, when I open a larger COBOL source with 100+ copybooks, zOSMF/Zowe somehow stacks up and crashes.  The first copybooks (20-30?) are received ok in temp folder. Can see in SDSF that I receive a S222 abend. 

Result is now that zOSMF api is inaccessible:

Retrieving response from zowe.List
Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       12
reason:   2
details: 
  - 
          =-=-=-=-=-=-=-=-=-=-=- CeaTsoRequest -=-=-=-=-=-=-=-=-=-=-=
      ceatso_requesttype:    1
      ceatso_userid:         UBIxxx
      ceatso_asid:           0x0000
      ceastso_logonproc:     IZUFPROC
      ceatso_numqueryreq:    0
      ceatso_numqueryrslt:   0
      ceatso_msgqueueid:     0x00000000
      ceatso_charset:        697
      ceatso_codepage:       1047
      ceatso_screenrows:     24
      ceatso_screencols:     80
      ceatso_account:        IZUACCT
      ceatso_group:          SYS1
      ceatso_region:         65536
      ceatso_instance:       0
      ceatso_apptag:         FSb71fe8
      ceatso_stoken:         0x0000000000000000
      ceatso_ascbaddr:       0x0
      ceatso_flags:          0x0
      ceatso_index:          0
      =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      
category: 3
message:  CeaTso request failed

What can be done to prevent this error ?

**Comment by phaumer** [comment]
Hello. This might be likely better discussed in the Zowe CLI github as we are just using the CLI technology to load the copybooks. But let me ask around if someone recognizes the error.

**Comment by hogstrom** [comment]
"S222 means job was cancelled by a user or operator without a dump."  This could be due to a job consuming too much resource, an operator issuing a cancel command but the end result is the same.  Can you share the job log of the failing job ?   If you want to share it in a more controlled method you can PM me or someone on the team.  We need to identify the reason underlying the cancel (S222)

**Comment by bearou** [comment]
> "S222 means job was cancelled by a user or operator without a dump." This could be due to a job consuming too much resource, an operator issuing a cancel command but the end result is the same. Can you share the job log of the failing job ? If you want to share it in a more controlled method you can PM me or someone on the team. We need to identify the reason underlying the cancel (S222)
> 
> Other items of information that would be useful are the z/OSMF JOB log (IZUSVR1) and even the messages from the zosmf USS log.

Thank you. I have both logs, but am a little unsure where to pm/post these... You mention 'the team' as in... ? 
Brgds Claus

**Comment by hogstrom** [comment]
@bearou you can pm me @hogstrom on slack

**Comment by bearou** [comment]
> @bearou you can pm me @hogstrom on slack or drop me an e-mail [matt@hogstrom.org](mailto:matt@hogstrom.org) I work for IBM but my contributions to Zowe are on my time. I'm happy to look at the logs and get back to you.

Sent pm on slack

**Comment by bearou** [comment]
We're still facing this problem, and zOSMF gateway (and Zowe CLI) has been unavailable for nearly 2 weeks... This is bad news for our internal Zowe project :(
The general theory is that there is a problem "Obtaining TSO address space" ... since Z Open Editor tries to retrieve 100+ copybooks.
Our providers have contacted IBM through other channels - but there are delays... 
Is there a way to "boot" zOSMF ?

**Comment by bearou** [comment]
Anyone? This is a major setback using zOSMF/Zowe. For more than 3 weeks the API has been unavailable, ie. VSCode not responding at all. We have opened an PMR @ IBM, but are we the only ones with this problem?

**Comment by Joey-ibm** [comment]
Hi, Claus
Sorry for slow response. I replied Isabel via email two days ago, not sure if you received the message. 

According to our investigation and latest update in the case TS003301691, the root cause is basically identified:
Open Editor calls z/OSMF data set REST API to retrieve content of data set members. Undercover, z/OSMF data set REST API calls z/OS CEA TSO launcher to allocate TSO address space as well as USS message queue. 

Opening a big program in Open Editor could trigger big amount of concurrent requests to z/OSMF in short time. This might trigger a problem of undercover z/OS CEA which cause the USS message queues allocated by CEA can not be released automatically. Such problem could spend message queue fast and eventually hit the maximum number of message queue set by system level or by process level. From that point on, CEA can not allocate message queue any more. That's why any z/OSMF services/plugins which depend on CEA TSO launcher can not work even restart z/OSMF. 

As a work around, increase the maximum number of message queue could allow CEA continue to work. From case TS003301691, it seems your system admin already did that, therefore, I assume your z/OSMF services has been restored. Avoid opening such size of program could reduce the chance to hit the problem. 

We are working with z/OS CEA team to further identify the problem and fix plan. Will let you know if any updates. Thanks!

Best regards!
Joey

**Comment by bearou** [comment]
Thank you @Joey-ibm! I Will close this issue and follow the PMR. I know that there will be attention on solving the problem
