### ISSUE TITLE
Pretty print

### ISSUE THREAD

**Issue by B-Teague** [IBM/zopeneditor-about#31]
Automatically format source code based on predefined settings.

Line up variables, etc.

**Comment by phaumer** [comment]
Added in v2.1.0: https://ibm.github.io/zopeneditor-about/Docs/zcodeformatting.html

**Comment by FALLAI-Denis** [comment]
Hi,

Is there an option to enable/disable source code formatting regardless of the presence of a zcodeformat.(json|yaml) file?

I didn't find any. I think it would be desirable to provide for this, both at the User level and at the Workspace level.

**Comment by phaumer** [comment]
@FALLAI-Denis we could file this as an enhancement. I am not sure about the value for disabling. If someone does not explicitly select format-on-save then nothing will be formatted. For governance I would rely more on code reviews such as GitHub Pull Requests.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer 

I wonder about the impact that reformatting the code could have on our coding assistance tools.

We have developed a VS Code extension that does the work described in [API for interacting with source code opened in Z Open Editor](https://github.com/IBM/zopeneditor-about/issues/93)

If the zcodeformat file does not exist...
If the user does not trigger a reformat (Shift-Alt-F)...
If automatic reformatting on entry or saving is not requested...
So no risk.
Otherwise, an option in the workspace's settings.json file would be the last chance to block a reformat; it is still necessary that this reformatting which is a standard function of VS Code is also under control of Z Open Editor.

**Comment by phaumer** [comment]
@FALLAI-Denis I see that for other languages VS Code allows disabling as well. We could add it for consistency. 
Btw. if the zcodeoformat file does not exist it will format using the defaults from the schema.
