### ISSUE TITLE
pli parsing errors on DFHBMSCA

### ISSUE THREAD

**Issue by nk2164** [IBM/zopeneditor-about#323]
We have an include for standard supplied DFHBMSCA copybook that has some map related constants. The parser seems to be failing on that copybooks . I have pasted the copybook variables on which it has failed.

Because of this , none of the other functionality like peek definitions etc. works. 

    ,DFHBMPSO CHAR (1) INIT ('.')  /* SHIFT OUT       */  

Gives ->  `Unexpected character ""  ignored`

    ,DFHBMPSI CHAR (1) INIT ('.')  /* SHIFT IN        */  

Gives -> `Unexpected character ""  ignored`

     /*  CODE FOR ERROR CODE                                    */ 
    ,DFHERROR CHAR (1) INIT ('.')  /* ERROR CODE-X'3F'*/ 

Gives ->`Unexpected character ""  ignored`

    ,DFH3270  CHAR (1) INIT ('{')  /* 3270     (X'C0')*/

Gives ->`Unexpected character "{"  ignored`

       ) STATIC INTERNAL;  

Gives ->`")" expected after this token   `

**Comment by walexand4z** [comment]
You must be using an old and unsupported version of CICS TS because if I look at the PL/I version of DFHBMSCA that was provided with CICS TS 4.2 it contained an enhancement to remove all embedded control characters and replace them with their hex notation.  This CICS TS enhancement was implemented to allow include files such as that one to be processed by modern tools.
Support for CICS TS 4.2 ended on 2018-09-30, so you must still be trying to use CICS TS 4.1 or CICS TS 3.x, all of which have been out of support for several years.
Moving up to a supported version of CICS TS such as 5.5, 5.6 or 6.1 would prevent this issue regarding DFHBMSCA.

**Comment by phaumer** [comment]
@nk2164 I moved you issue into this repository.

**Comment by nk2164** [comment]
@walexand4z . Thanks a lot. I checked we are on 5.6 , but looks like our copybook libs need to be updated. Appreciate your response.
@phaumer , sure. Thanks.
