### ISSUE TITLE
Manage propertygroups by language

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#72]
## Description of the enhancement requested

Propertygroups are used to indicate the search paths for COPYBOOKs / INCLUDEs.
These search paths can be different from one language to another, in particular when the libraries are already organized by languages.
For example, there is no need to search for a member in the SYS1.MACLIB library when editing a Cobol program.

The "propertygroups" should be able to be defined by language, or else have a "language" attribute to be able to be selected according to the source code being edited.

**Comment by phaumer** [comment]
Can you clarify more you specific use cases for this @FALLAI-Denis ? 
- Right now you can have multiple property groups in an array and use each entry for different languages. Do you have performance in mind, that it should not look in places that are not relevant for the language?
- We are assuming that customer do not mix languages a lot and hence assumed that they have property groups defined in their workspace settings - perhaps as part of their git repo - and not user settings so that each workspace only lists the property groups specific to the application in that workspace.

**Comment by FALLAI-Denis** [comment]
Note: language = programming language = language id

Z Open Editor must not impose an organization, either at the level of GIT repositories or outside of GIT repositories.

### About the organization of GIT repositories

Our GIT repositories are organized by Application, and therefore a GIT repository can potentially contain sources using different languages, (although in practice this is rarely the case).
In our organization, a GIT repository will contain the COPYBOOKs / INCLUDEs of the current Application, which will be declared with the "local" type, and the COPYBOOKs / INCLUDEs of the other Applications will be declared with the "mvs" type for a search on the z/OS host, (The "local" search must have priority over the "mvs" search).

Furthermore, when a program of an Application A must interface with a program of an Application B, it generally uses a COPYBOOK / INCLUDE declared by the Application B, and therefore managed in the GIT repository of the Application B. 
In order not to need access to the GIT repository of other Applications, all COPYBOOKs / INCLUDEs are also stored (as read only) and accessible on the z/OS host (also need for compilers wich don't work with GIT repository), today as members of PDS, probably tomorrow, as as file in a USS path, (to exceed the limit of 8 characters in the names of COPYBOOKs / INCLUDEs).

Note: does the search for COPYBOOK in Cobol by Z Open Editor work for USS storage with the same rules as those of the Enterprise Cobol compiler, ie search with addition of a suffix, in the order: .cpy,. CPY, .cbl, .CBL, .cob, and .COB ?
See [Copy member search order](https://www.ibm.com/support/knowledgecenter/SS6SG3_6.2.0/lr/ref/rlcdscopc.html)

### About search for by language

The same COPYBOOK / INCLUDE name can exist for several different languages, because it represents the same information, coded differently depending on the language (case of SQLCA which exists for all programming languages, sometimes implicit, sometimes explicit).
In this case, you should be able to target the search to a set of “local” or “mvs” locations, depending on the programming language (language id).
We already have the case for the declarations used in Cobol language, Assembler language and C language.

**Comment by phaumer** [comment]
Thanks a lot for this summary. Support for remote USS locations is not yet on our roadmap. You could file this a separate item if you want.

**Comment by davidkjackson54** [comment]
The zopeneditor.propertygroups has a strange layout:
This is valid - but I see no advantage in having 2 entries as both groups are searched.  
The only requirement is that the name tag is unique.  
It is almost as if the capability to have multiple groups was considered but then no means to select one group over an another.
It would be  a problem if 2 copybook members were to exist with the same name for 2 different languages. In the example below, I would not make sense for the COBOL copy SYSLIB to be scanned for an ASM program. 
{
        "name": "mvs-members",
        "type": "mvs",
        "syslib": [
            "DJACKSO.TEST.COBOL",
        ],
      }
      {
        "name": "mvs2-members",
        "type": "mvs",
        "syslib": [
            "DJACKSO.TEST.ASM,
        ],
      }

This is backed up by the comment in the documentation where it states:
**Performance warning:** For performance reasons, if your specified property groups contain a glob pattern that returns more than 20 directories to search, revise the search pattern to match less in order to increase performance for finding copybooks and include files.

by not allowing a more granular language SYSLIB, there is every likelihood that the search order could easily extend beyond 20+ libraries.

**Comment by FALLAI-Denis** [comment]
Hi,

There may be an interest in declaring several propertygroups, in fact declaring two, if one is declared at "workspace" level and shared by all users (workspace = Git repository), and if the other is declared at "user level" and specific to that user.

In the event of multiple declarations, it would be necessary to be able to manage the priority in a way that may be more explicit than the simple order of declaration in the "settings.json" file (under VS Code).

Can also manage an "active" / "inactive" flag to be able to easily inhibit certain searches without "destroying" the declarations in the "settings.json" file.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 1.1. We extended property groups with language and compiler option properties:
https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#language-scoping
