### ISSUE TITLE
Search pattern should be able to include member name

### ISSUE THREAD

**Issue by oakmount66** [IBM/zopeneditor-about#80]
We have source dataset with more than 200k programs and there is a limit in how many members we can fetch through the RSE profile (20.000).
In TSO/ISPF you can view/edit dataset with a pattern on member level and we like to have a similar opportunity in VScode.
A solution could be like below 
![image](https://user-images.githubusercontent.com/60236192/92485203-ed0e4c80-f1ea-11ea-9c54-bbbc319269a9.png)

Thanks
/Lars

**Comment by gplambert** [comment]
@oakmount66 -   thanks, we will look into adding this as a future enhancement.

**Comment by phaumer** [comment]
@oakmount66 is this specifically for the RSE API or are you using z/OSMF? 
I think we should discuss this in the Zowe Explorer community first.

**Comment by oakmount66** [comment]
Hi Peter.
We use both. We use z/OSMF because here we can set the Ecoding, so that our national characters can be presented correctly and we use RSE to fetch COBOL copybooks.
/Lars.

**Comment by phaumer** [comment]
This one was fixed in Zowe Explorer with 
- https://github.com/zowe/vscode-extension-for-zowe/issues/868
- https://github.com/zowe/vscode-extension-for-zowe/issues/1112
- https://github.com/zowe/vscode-extension-for-zowe/issues/1210

In addition this refinement is planned as well: https://github.com/zowe/vscode-extension-for-zowe/issues/1241
